### ISSUE TITLE
Propose fixed folder structure for ICONS standard

### ISSUE THREAD

**Issue by jepke** [Mygod/pokemon-icon-postprocessor#2]
-     gym
-     invasion
-     pokemon
-     raid
-     reward
-     team
-     type
-     weather
-     misc

**Comment by Mygod** [comment]
No.

**Comment by jepke** [comment]
I need a fixed folder structure for PMSF or we simply can't support ICONS.

**Comment by ccev** [comment]
> No.

great "Intermapping Cooperative" project you got here
