### ISSUE TITLE
migrate.js error

### ISSUE THREAD

**Issue by ghost** [Mygod/pokemon-icon-postprocessor#3]
Thank you for your work on this repo, Main.js works no problem but since I use Shuffle icons and MapJS I wanted to use migrate.js and the following happens when trying to run it now.
```
node migrate.js pmsf /user/shuffle/PMSF_icons_large /user/done
Reading game master...
/user/conv/migrate.js:160
                extractForms(pokemon, template, pokemonId, (form) => POGOProtos.Enums.Form[form]);
                                                                                      ^

TypeError: Cannot read properties of undefined (reading 'Form')
    at /user/conv/migrate.js:160:87
    at extractForms (/user/conv/migrate.js:43:24)
    at /user/conv/migrate.js:160:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by PoGoJoshS** [comment]
Well I got it to run by replacing the POGOProtos destinations but it isn't recognizing a lot of forms so it's missing about 1000 images. Going to dive back in later when I have more time.

**Comment by PoGoJoshS** [comment]
Well I got it to run by updating the POGOProtos addresses to what's in main.js. But it's not recognizing a lot of forms so it's missing about 1000 images. Going to dive back in later when I have more time. Should probably just switch to ReactMap but my users don't like change and are used to MapJS.

**Comment by ghost** [comment]
Got it to run by updating the POGOProtos addresses to what's in main.js. But it's not recognizing a lot of forms so it missed about 1000 images. Probably wiser to spend this time switching to ReactMap...

**Comment by Mygod** [comment]
migrate.js has been archived so no more support on that script.
